import { configDotenv } from "dotenv";

configDotenv();

export const { 
    PORT, NODE_ENV,
    MONGO_URI,
    REDIS_PASSWORD, REDIS_HOST, REDIS_PORT,
    ACCESS_TOKEN_SECRET, REFRESH_TOKEN_SECRET,
    CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET,
    STRIPE_SECRET_KEY, STRIPE_WEBHOOK_SECRET,
    CLIENT_URL
 } = process.env;